variable "ibm_region" {}
variable "image_id" {}
variable "profile" {}
variable "zone" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "security_group_id" {}
variable "ssh_key_id" {}
variable "instance_name" {}
